server:
  port: 8070

application:
  security:
    jwt:
      secret-key: McvbIKwPaVjhmKBwFUdHDXzvFWEAZgaJ8XJr6cBsvNKPI9VUAW7GzFMV6ZhHsI
      expiration: 86400000  # 1 día
spring:
  application:
    name: app_hc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://harmonichat.c5y240664x6a.us-east-2.rds.amazonaws.com:5432/app_hc
    username: postgres
    password: postgre123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 5000
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
  azure:
    storage:
      connection-string: "DefaultEndpointsProtocol=https;AccountName=harmonichat;AccountKey=EhRSPUxrdIol/BcdnkZifwDzTSb8JIwdSLpe7i04fh83qGRJnJ1oMWYsG+tWmPQgii1VVQ7qh+nn+AStWzLwYQ==;EndpointSuffix=core.windows.net"
      containers:
        emotions_diary: "emotions"
        posts: "posts"
        chat: "messages"
      tokens:
        emotions: "sp=racwdli&st=2025-04-02T21:00:30Z&se=2025-12-04T05:00:30Z&sv=2024-11-04&sr=c&sig=uUtzG5ISis14LlMW5CSk5D2KP%2F6INHbS%2Bai6pt2woSs%3D"
        posts: "sp=racwdli&st=2025-04-02T21:45:05Z&se=2025-12-02T05:45:05Z&sv=2024-11-04&sr=c&sig=SydTXcIYLS3o%2FFQoHiBJlfLEQQ9ifcMEj39B5gUDOlc%3D"
        messages: "sp=racwdli&st=2025-04-08T19:28:24Z&se=2025-12-09T03:28:24Z&sv=2024-11-04&sr=c&sig=MU1eJTal12qRdx%2BHYXNHCA3W2k3HF87Ih2rrX1gR%2BuQ%3D"
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: harmonichat025@gmail.com
    password: dypa sexx gsio xyxu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        smtp.ssl.trust: smtp.gmail.com
        from: "HarmoniChat <no-reply@harmonichat.com>"
        replyto: "soporte@harmonichat.com"
  zerobouce:
    api:
      key: "af623b01e33243fd9469f07f8cc64bf0"
  gemini:
    api:
      key: "AIzaSyBLV23iC90IJ46dXI70axOcnDQG_DUggsw"
    location: "us-central1"
    project:
      id: "gen-lang-client-0542591181"