server:
  port: 8090

spring:
  application:
    name: hc-emotion-diary
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://harmonichat.c5y240664x6a.us-east-2.rds.amazonaws.com:5432/emotionsDb
    username: postgres
    password: postgre123
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix: DEBUG
    org.springframework.cloud: DEBUG