server:
  port: 8070

application:
  security:
    jwt:
      secret-key: McvbIKwPaVjhmKBwFUdHDXzvFWEAZgaJ8XJr6cBsvNKPI9VUAW7GzFMV6ZhHsI
      expiration: 86400000  # 1 día
spring:
  application:
    name: app_hc
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://harmonichat.c5y240664x6a.us-east-2.rds.amazonaws.com:5432/app_hc
    username: postgres
    password: postgre123
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
  azure:
    storage:
      connection-string: "DefaultEndpointsProtocol=https;AccountName=harmonichat;AccountKey=EhRSPUxrdIol/BcdnkZifwDzTSb8JIwdSLpe7i04fh83qGRJnJ1oMWYsG+tWmPQgii1VVQ7qh+nn+AStWzLwYQ==;EndpointSuffix=core.windows.net"
      token-sas: "sp=racwdli&st=2025-03-31T05:29:38Z&se=2025-08-01T13:29:38Z&sv=2024-11-04&sr=c&sig=vCphMM8wafsgdiTztT7VV17k1zIIRilNu262q5UX2AU%3D"
      containers:
        emotions_diary: "emotions"
        posts: "posts"
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB