name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          echo "📦 Instalando dependencias..."
          mvn clean install -DskipTests

      - name: Run tests
        run: |
          echo "🧪 Ejecutando pruebas..."
          mvn test"

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy backend to Railway
        run: railway up --service HC-Backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_BACKEND }}
